20

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,78 +1,72 @@
 name: chocolatine
 run-name: ${{ github.actor }} is the project chocolatine
 on:
-   push:
-     branches-ignore:
+  push:
+    branches-ignore:
        - ! 'ga-ignore-*'
-   pull_request:
-     branches-ignore:
+  pull_request:
+    branches-ignore:
        - ! 'ga-ignore-*'
-
 env:
   MIRROR_URL: git@github.com:amyrath/try_chocolatine.git
   EXECUTABLES: mysh
-
 jobs:
   check_coding_style:
-    Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     container: ghcr.io/epitech/coding-style-checker:latest
     steps:
       - name: the checkout base
-      - uses: actions/checkout@v4
+        uses: actions/checkout@v4
       - name: chech coding style
-      - run: |
-          check.sh $(pwd) $(pwd)
+        run: check.sh $(pwd) $(pwd)
+      - name: verify the coding style file
+        run: |
           if [coding-style-reports.log]; then
-          cat coding-style-reports.log
-          exit 1
+            cat coding-style-reports.log
+            exit 1
           fi
   check_program_compilation:
     needs: check_coding_style
-    Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker
     steps:
       - name: the checkout base
-      - uses: actions/checkout@v4
+        uses: actions/checkout@v4
       - name: check the compilation
-      - run: make
-      - timeout-minutes: 2
-    steps:
+        run: make
+        timeout-minutes: 2
       - name: clean the repot
-      - run: make clean
+        run: make clean
       - name: control executable
         run: |
-         for exe in $(echo $EXECUTABLES); do
-         if [! -x "$exe"]; then
-         echo "execution is fail"
-         exit 1
-         fi
+          for exe in $(echo $EXECUTABLES); do
+            if [! -x "$exe"]; then
+              echo "execution is fail"
+              exit 1
+            fi
   run_tests:
     needs: check_program_compilation
-    Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     container: epitechcontent/epitest-docker
     steps:
        - name: the checkout base
-       - uses: actions/checkout@v4
+         uses: actions/checkout@v4
        - name: check the unit tests
-       - run: |
+         run: |
           make tests_run
-          timeout 120
           exit 1
+         timeout-minutes: 2
   push_to_mirror:
     needs: run_tests
-    Explore-GitHub-Actions:
     runs-on: ubuntu-latest
     steps:
       - name: the checkout base
-      - uses: actions/checkout@v4
+        uses: actions/checkout@v4
       - name: create the key
-      - run: |
+        run: |
           mkdir ~/.ssh
           echo "$GIT_SSH_PRIVATE_KEY" > ~/.ssh/stock
           chmod 600 ~/.ssh/stock
-      - name: push in mirror
-          git remote add mirror "$MIRROR_URL"
-          git push --mirror mirror
+#      - name: push in mirror
+              #git remote add mirror "$MIRROR_URL"
+              #git push --mirror mirror
